# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Game(object):
    def setupUi(self, Game):
        Game.setObjectName("Game")
        Game.resize(1000, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Game.sizePolicy().hasHeightForWidth())
        Game.setSizePolicy(sizePolicy)
        Game.setMinimumSize(QtCore.QSize(1000, 675))
        Game.setStyleSheet("\n"
"QWidget{\n"
"    background-color: rgb(41, 49, 51);\n"
"}\n"
"QLabel {\n"
"    border: 1px solid black;\n"
"    background-color: white;\n"
"}\n"
"QLabel {\n"
"    color: rgb(245, 245, 245);    \n"
"}\n"
"QLineEdit {\n"
"    background-color: black;\n"
"    border: 1px solid white;\n"
"    border-radius: 7px;\n"
"    color: rgb(156, 156, 156);    \n"
"}\n"
"QPushButton{\n"
"background-color: black;\n"
"    font-family: Lucida Sans Unicode;\n"
"    font: 10px;\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(156, 156, 156);\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton::disabled{\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: black;\n"
"}\n"
"QTextEdit {\n"
"    background-color: black;\n"
"    border: 1px solid white;\n"
"    border-radius: 7px;\n"
"    color: rgb(156, 156, 156);    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Game)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setObjectName("label")
        self.chat = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.chat.setEnabled(True)
        self.chat.setGeometry(QtCore.QRect(800, 0, 200, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat.sizePolicy().hasHeightForWidth())
        self.chat.setSizePolicy(sizePolicy)
        self.chat.setMouseTracking(False)
        self.chat.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.chat.setObjectName("chat")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 610, 991, 52))
        self.widget.setObjectName("widget")
        self.buttons = QtWidgets.QHBoxLayout(self.widget)
        self.buttons.setContentsMargins(0, 0, 0, 0)
        self.buttons.setSpacing(0)
        self.buttons.setObjectName("buttons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttons.addItem(spacerItem)
        self.startGame = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startGame.sizePolicy().hasHeightForWidth())
        self.startGame.setSizePolicy(sizePolicy)
        self.startGame.setMinimumSize(QtCore.QSize(100, 0))
        self.startGame.setObjectName("startGame")
        self.buttons.addWidget(self.startGame)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttons.addItem(spacerItem1)
        self.changeRoom = QtWidgets.QPushButton(parent=self.widget)
        self.changeRoom.setMinimumSize(QtCore.QSize(100, 0))
        self.changeRoom.setObjectName("changeRoom")
        self.buttons.addWidget(self.changeRoom)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttons.addItem(spacerItem2)
        self.exit = QtWidgets.QPushButton(parent=self.widget)
        self.exit.setMinimumSize(QtCore.QSize(100, 0))
        self.exit.setObjectName("exit")
        self.buttons.addWidget(self.exit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttons.addItem(spacerItem3)
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(800, 570, 202, 26))
        self.widget1.setObjectName("widget1")
        self.inputLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.inputLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.inputLayout.setContentsMargins(0, 0, 0, 0)
        self.inputLayout.setSpacing(0)
        self.inputLayout.setObjectName("inputLayout")
        self.input = QtWidgets.QLineEdit(parent=self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setMinimumSize(QtCore.QSize(150, 0))
        self.input.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.input.setFont(font)
        self.input.setAcceptDrops(True)
        self.input.setFrame(True)
        self.input.setObjectName("input")
        self.inputLayout.addWidget(self.input)
        self.send = QtWidgets.QPushButton(parent=self.widget1)
        self.send.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send.sizePolicy().hasHeightForWidth())
        self.send.setSizePolicy(sizePolicy)
        self.send.setMinimumSize(QtCore.QSize(50, 0))
        self.send.setMaximumSize(QtCore.QSize(50, 16777215))
        self.send.setObjectName("send")
        self.inputLayout.addWidget(self.send)
        self.startGame.raise_()
        self.changeRoom.raise_()
        self.exit.raise_()
        self.input.raise_()
        self.chat.raise_()
        self.send.raise_()
        self.label.raise_()
        Game.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Game)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        Game.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Game)
        self.statusbar.setObjectName("statusbar")
        Game.setStatusBar(self.statusbar)

        self.retranslateUi(Game)
        QtCore.QMetaObject.connectSlotsByName(Game)

    def retranslateUi(self, Game):
        _translate = QtCore.QCoreApplication.translate
        Game.setWindowTitle(_translate("Game", "Game"))
        self.startGame.setText(_translate("Game", "start game"))
        self.changeRoom.setText(_translate("Game", "change room"))
        self.exit.setText(_translate("Game", "exit"))
        self.send.setText(_translate("Game", "send"))
